kind: pipeline
type: docker
name: test-and-build

steps:
  # ============ TESTS ============

  - name: test-mysql-api
    image: python:3.11-slim
    commands:
      - cd mysql-api
      - pip install -r requirements.txt
      - pip install pytest httpx
      - python -c "from main import app; print('MySQL API syntax OK')"

  - name: test-spark-api
    image: node:20-alpine
    commands:
      - cd spark-api
      - npm install
      - node -e "require('./index.js'); console.log('Spark API syntax OK')" || true

  - name: test-oauth2-server
    image: elixir:1.15-alpine
    commands:
      - apk add --no-cache build-base
      - cd oauth2-server
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile

  # ============ BUILD & PUSH ============

  - name: build-mysql-api
    image: plugins/docker
    settings:
      registry:
        from_secret: harbor_registry
      repo:
        from_secret: harbor_repo_mysql_api
      dockerfile: mysql-api/Dockerfile
      context: mysql-api
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true
    depends_on:
      - test-mysql-api

  - name: build-spark-api
    image: plugins/docker
    settings:
      registry:
        from_secret: harbor_registry
      repo:
        from_secret: harbor_repo_spark_api
      dockerfile: spark-api/Dockerfile
      context: spark-api
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true
    depends_on:
      - test-spark-api

  - name: build-oauth2-server
    image: plugins/docker
    settings:
      registry:
        from_secret: harbor_registry
      repo:
        from_secret: harbor_repo_oauth2
      dockerfile: oauth2-server/Dockerfile
      context: oauth2-server
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true
    depends_on:
      - test-oauth2-server

  - name: build-spark-server
    image: plugins/docker
    settings:
      registry:
        from_secret: harbor_registry
      repo:
        from_secret: harbor_repo_spark
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true

  # ============ HARBOR VULNERABILITY SCAN ============

  - name: scan-mysql-api
    image: curlimages/curl:latest
    environment:
      HARBOR_REGISTRY:
        from_secret: harbor_registry
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
      HARBOR_PROJECT:
        from_secret: harbor_project
    commands:
      - |
        curl -sk -X POST \
          -u "$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          "https://$HARBOR_REGISTRY/api/v2.0/projects/$HARBOR_PROJECT/repositories/mysql-api/artifacts/latest/scan"
      - echo "Scan triggered for mysql-api:latest"
    depends_on:
      - build-mysql-api

  - name: scan-spark-api
    image: curlimages/curl:latest
    environment:
      HARBOR_REGISTRY:
        from_secret: harbor_registry
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
      HARBOR_PROJECT:
        from_secret: harbor_project
    commands:
      - |
        curl -sk -X POST \
          -u "$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          "https://$HARBOR_REGISTRY/api/v2.0/projects/$HARBOR_PROJECT/repositories/spark-api/artifacts/latest/scan"
      - echo "Scan triggered for spark-api:latest"
    depends_on:
      - build-spark-api

  - name: scan-oauth2-server
    image: curlimages/curl:latest
    environment:
      HARBOR_REGISTRY:
        from_secret: harbor_registry
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
      HARBOR_PROJECT:
        from_secret: harbor_project
    commands:
      - |
        curl -sk -X POST \
          -u "$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          "https://$HARBOR_REGISTRY/api/v2.0/projects/$HARBOR_PROJECT/repositories/oauth2-server/artifacts/latest/scan"
      - echo "Scan triggered for oauth2-server:latest"
    depends_on:
      - build-oauth2-server

  - name: scan-spark-server
    image: curlimages/curl:latest
    environment:
      HARBOR_REGISTRY:
        from_secret: harbor_registry
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
      HARBOR_PROJECT:
        from_secret: harbor_project
    commands:
      - |
        curl -sk -X POST \
          -u "$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          "https://$HARBOR_REGISTRY/api/v2.0/projects/$HARBOR_PROJECT/repositories/spark-server/artifacts/latest/scan"
      - echo "Scan triggered for spark-server:latest"
    depends_on:
      - build-spark-server

trigger:
  branch:
    - master
    - main
  event:
    - push
    - pull_request
